### ISSUE TITLE
make article uid editable

### ISSUE THREAD

**Issue by akinaru-lu** [akinaru-lu/lmm#615]
for better SEO policy

### TODO
- [ ] migrate article uid from 8 length to 32 length (by default)
- [ ] change uid validation policy
- [ ] make uid changable
- [ ] manager page
