### ISSUE TITLE
users view

### ISSUE THREAD

**Issue by akinaru-lu** [akinaru-lu/lmm#661]
# TODO
- [x] users count #662
- [x] [api] testing PUT /v1/users/:user/role #664
- [ ] [api] testing GET /v1/users
- [x] [manager] change role #665

### reference
https://github.com/akinaru-lu/lmm/pull/660
